server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.bksoftwarevn.com:6633/backend_class
    username: backend
    password: fcojhsbtxzdu

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        event:
          merge:
            entity_copy_observer: allow
    show-sql: true
